#!/bin/bash
# Thema 1

for file     #on input parameters(file list)
do
if [ ! -f $file ]
then
echo "ONLY Files are allowed as Program parameters"
else
#head -n 5 $file,,,var=($(echo $(head -n 4 input1)))
#awk -F ":" '{print $1}' input1
#NEW :  vr=($(echo $(awk -F ":" '{print $1}' $file)))
unset X Y				     #clearing variable(could cause problems)
X=($(echo $(awk -F ":" '{print $1}' $file))) #choose the group thats left from ":"
Y=($(echo $(awk -F ":" '{print $2}' $file)))
len=${#X[@]}   			             #length of each file
#########################---- C A L C U L A T I O N S ----################################
sum_x=0
sum_y=0
sum_xy=0
sum_x2=0
err=0
for (( i = 0 ; i <= $len - 1; i++))
do

sum_x=$(echo "scale=2; ${X[i]}+$sum_x" | bc)
sum_y=$(echo "scale=2; ${Y[i]}+$sum_y" | bc)
sum_xy=$(echo "scale=2; (${X[i]}*${Y[i]}) + $sum_xy" | bc)
sum_x2=$(echo "scale=2; (${X[i]}*${X[i]}) + $sum_x2" | bc)

done
###calc a,b after all sums are known

a=$(echo "scale=2; (($len*$sum_xy)-($sum_x*$sum_y)) / (($len*$sum_x2)-($sum_x*$sum_x))" | bc)
b=$(echo "scale=2; ($sum_y-($a*$sum_x)) / $len" | bc)

for (( i = 0 ; i <= $len - 1; i++))	#final error calculation
do

err=$(echo "scale=2; (${Y[i]} - ($a*${X[i]} + $b))*(${Y[i]} - ($a*${X[i]} + $b)) + $err" | bc)

done
##########################################################################################
echo  "FILE: $file, a=$a b=$b c=1 err=$err"
fi
done

