#!/bin/bash
# Thema 1

for file     #on input parameters(file list)
do
if [ ! -f $file ]   #Checking if the input is a file type
then
echo "Your inputs are not a file type"
else

myfile=$(basename $file)   		     #In order to take only the name of the file and not the full path attached to it
unset X Y				     #clearing variable(could cause problems)
X=($(echo $(awk -F ":" '{print $1}' $file))) #choose the group thats left from ":"
Y=($(echo $(awk -F ":" '{print $2}' $file))) #choose the group thats right from ":"
len=${#X[@]}   			             #length of each file
#########################---- C A L C U L A T I O N S ----################################
sum_x=0
sum_y=0
sum_xy=0
sum_x2=0
err=0
for (( i = 0 ; i <= $len - 1; i++))
do
 
sum_x=$(echo "scale=2; ${X[i]}+$sum_x" | bc)
sum_y=$(echo "scale=2; ${Y[i]}+$sum_y" | bc)
sum_xy=$(echo "scale=2; (${X[i]}*${Y[i]}) + $sum_xy" | bc)
sum_x2=$(echo "scale=2; (${X[i]}*${X[i]}) + $sum_x2" | bc)

done
###calc a,b after all sums are known
#Firstly,we check the denominator
c=1

if (( $(echo "scale=2; ($len*$sum_x2) == ($sum_x*$sum_x)" | bc) ))
then
    #When X is static,we mean a vertical line,--> c=0, -> X=-b/a ,with a random a
    c=0
    b=-${X[0]}
    a=1      ##lets say 1,it could be anything
else
c=1
a=$(echo "scale=2; (($len*$sum_xy)-($sum_x*$sum_y)) / (($len*$sum_x2)-($sum_x*$sum_x))" | bc)
b=$(echo "scale=2; ($sum_y-($a*$sum_x)) / $len" | bc)
fi


for (( i = 0 ; i <= $len - 1; i++))	#final error calculation
do

err=$(echo "scale=2; (${Y[i]} - ($a*${X[i]} + $b))*(${Y[i]} - ($a*${X[i]} + $b)) + $err" | bc)

done
##########################################################################################
echo  "FILE: $myfile, a=$a b=$b c=$c err=$err"


fi
done
